#ifndef PROPCODES_H
#define PROPCODES_H

#define PROPCODE_GROUP 1
#define PROPCODE_VISGROUP 2
#define PROPCODE_NODE 3
#define PROPCODE_PROP 4
#define PROPCODE_SIGN 5
#define PROPCODE_SIGN_BASELINE 6
#define PROPCODE_SIGN_TEXT 7
#define PROPCODE_SIGN_GRAPHIC 8
#define PROPCODE_FLAT_BUILDING 9
#define PROPCODE_WALL 10
#define PROPCODE_WINDOWS 11
#define PROPCODE_CORNICE 12
#define PROPCODE_LANDMARK_BUILDING 13
#define PROPCODE_ANIM_PROP 14
#define PROPCODE_INTERACTIVE_PROP 15
#define PROPCODE_ANIM_BUILDING 16
#define PROPCODE_DOOR 17
#define PROPCODE_FLAT_DOOR 18
#define PROPCODE_STREET 19
#define PROPCODE_SUIT_POINT 20
#define PROPCODE_BATTLE_CELL 21
#define PROPCODE_SUIT_EDGE 22

#define PROPCODE_SPECIAL_LEVEL_UP 255

#endif
